### ISSUE TITLE
Caffeine Wrapped calculation is off

### ISSUE THREAD

**Issue by KAMiKAZOW** [chaosdorf/mete#143]
Caffeine *Wrapped* calculation is off. If caffeine is x mg per 100 ml and a bottle is 500 ml, the overall caffeine of Club in the following example is 20*5*3, instead of 20*3.

![image](https://github.com/chaosdorf/mete/assets/3259076/fb33721f-b57f-4c97-91cb-27d88b3480c6)

![image](https://github.com/chaosdorf/mete/assets/3259076/9b34b267-162f-4887-af80-dd69995bb433)

**Comment by YtvwlD** [comment]
thanks!
