### ISSUE TITLE
badly structured drinks menu and wrong labels

### ISSUE THREAD

**Issue by derf** [chaosdorf/mete#17]
* "Hausmarke Ekel-Cola" should be labeled "Hausmarke Lakritz-Cola". Also, there's the "Hausmarke Kaffee-Cola" available and missing in mete
* Drinks should be visibly grouped by price (e.g. one line for each price). the current status makes the payment take quite a while if one really wants to search for the bought drink and not click on the next one matching the price.

**Comment by YtvwlD** [comment]
Restructuring this to #23.
