### ISSUE TITLE
Inconsistent Ruby versions specified

### ISSUE THREAD

**Issue by nomaster** [chaosdorf/mete#40]
The file `.ruby-version` states Ruby version 2.3.0, whereas `Dockerfile` says 2.4.

I am convinced we are targeting Ruby 2.4 at the moment and I strongly recommend using Docker for development. Therefore, the `.ruby-version` file should be removed.

Probably, the intended workflow to develop with Docker should be documented in the readme file.

**Comment by nomaster** [comment]
@marudor you added the file in question. Please comment on this!

**Comment by YtvwlD** [comment]
I moved both to 2.5.
