### ISSUE TITLE
please add some lines on howto config/admin

### ISSUE THREAD

**Issue by cccfr** [chaosdorf/mete#61]

**Comment by cccfr** [comment]
especially config pictures from users

**Comment by Bouni** [comment]
I would like to have some more documentation as well.
Especially how to build and run the docker image.
@cccfr Can you give some information how you got your setup up and running?

**Comment by YtvwlD** [comment]
Currently, users can't upload their own images. Gravatar is being used.
But this might change, see https://github.com/Space-Market/API/pull/2.

**Comment by YtvwlD** [comment]
To get the server running quickly, you can use docker-compose.
Or you can use Bundler as described [here](https://github.com/chaosdorf/mete/blob/master/Setup.md).
Or something in between.

(Yes, there's documentation missing.)

**Comment by YtvwlD** [comment]
I know this issue is almost two years old, but is that enough documentation? Or did I miss something?

**Comment by viisauksena** [comment]
i had a quick look over it, seems fine
