### ISSUE TITLE
Drink availability

### ISSUE THREAD

**Issue by nomaster** [chaosdorf/mete#9]
Users can mark drinks as unavailable.

Unavailable drinks are shown last in the list with a grayed-out logo.

Drinks can be made available again and are toggled to availble on buying a drink automatically.

**Comment by YtvwlD** [comment]
- [x] Users can mark drinks as unavailable.
 - [ ] Unavailable drinks are shown last in the list with a grayed-out logo.
 - [ ] Drinks can be made available again and are toggled to availble on buying a drink automatically.

(see https://github.com/chaosdorf/mete/compare/master...YtvwlD:issue9?expand=1)
