### ISSUE TITLE
Price is locked to 1.50

### ISSUE THREAD

**Issue by fosBHY** [chaosdorf/mete#98]
When creating a Drink in a fresh install made with the docker-compose.yaml (only changed ports) the Price of the Drinks cannot be changed.

Price*e.g. 1.50; locked due to vandalism

**Comment by nomaster** [comment]
This is a nasty little feature of the UI. The property is not really read-only, only the form field is disabled. When you use the inspector panel of your browser, you can remove that property and use the form as expected.

Maybe we will come up with a better solution. I would love to see some PR. 😃

**Comment by fosBHY** [comment]
thank you!

for other people finding this who are not into docker and programming, I found out how to disable the disable (and change the UI for example to translate it):

after docker-compose up containers are running. in another terminal 
`sudo docker exec -it mete_backend_1 sh`

in there you can delete the "disabled" tag with 
`vi /app/app/views/drinks/_form.html.haml`

afterwards, restart containers.

**Comment by YtvwlD** [comment]
You can also use the API to change the values (or eg. [metecli](https://github.com/ytvwld/metecli)).
