### ISSUE TITLE
uncontrolled behaviour when listing users

### ISSUE THREAD

**Issue by fosBHY** [chaosdorf/mete#99]
when listing users in /users or by going to docRoot I'd expect either 0 users to be shown so people have to go for their first letter or I'd rather expect all users to be shown for quick selection.

instead most of the time on my instance with 3 testusers it will show none. sometimes it will show some users for a splitsecond then they vanish again. sometimes (like every 15th refresh of the page) some users are shown.

any clues where to start looking for this problem?

edit: happens in webUI, not in meteroid2

**Comment by YtvwlD** [comment]
The server should always return all users (check the HTML source), but client-side JavaScript filters those according to the first letter. You can select the letter by pressing on the bar at the top. You can see this filter also in the URL fragment. The initial filter is chosen randomly on page load.

Does this make sense?

(This does only really make sense for lots of users, but it is currently always enabled, please see #77 for details.)

**Comment by fosBHY** [comment]
ah yes I see. 

from my Userpoint of view: a random filter does not make sense in my opinion. For our project (30 people) it would be easiest to list all users. 

do you have hints on how to disable "random" chosen filters? I'm very bad with html, javascript and, well any language.

**Comment by YtvwlD** [comment]
For a quick and dirty fix you could try deleting `app/assets/javascripts/users.js`.

I'm trying to come up with a better solution, but this could take a few days.

(As a bit of background story: We have got many users (more than 200, if I'm not mistaken) and everyone wanted to be the first one in the list, so they added emojis and other characters to their username. This randomness tries to prevent this sort of cheating.)

**Comment by fosBHY** [comment]
Unfortunately this did not help, neither renaming nor completely removing the file from the folder.
this brought no change at all which seems weird. I did this again from within the container  `docker exec -it mete_backend_1 sh`

the backgroundstory is understandable :) thanks for your help.

**Comment by fosBHY** [comment]
Thanks for your work!
Im sure it works for you and Im probably doing stuff wrong but I manually changed / copied the files changed in this pull request into my mete instance and now no users are listed even when clicking on the right letter. 

I fundamentally do not understand docker though so there might be a problem.

**Comment by YtvwlD** [comment]
The problem is that our Docker image ships minified versions of the assets. If you modify the source files in the image it will have no effect, because Mete still uses the compiled ones. Please try running `bundle exec rake assets:precompile`.

**Comment by fosBHY** [comment]
the bundle exec did not help, however pulling the new image did :) Thanks a lot for your help and your work and this tool in general.
